const translations = {
  ro: {
    skip: "Sari la conținut",
    navLabel: "Navigație principală",
    mobileNavLabel: "Navigație mobilă",
    tickerAria: "Ce construiește GoByde",
    googlePlaySoon: "Google Play — în curând",
    appStoreSoon: "App Store — în curând",
    navGames: "Jocuri",
    navComingSoon: "În lucru",
    navStudio: "Despre noi",
    navContact: "Contact",
    menu: "Meniu",
    metaDescription: "GoByde este un studio independent de jocuri și aplicații mobile. Primul nostru joc este Aura Clicker.",
    ogTitle: "GoByde — Jocuri și aplicații mobile",
    ogDescription: "Construim jocuri și aplicații mobile simple de folosit și plăcute de păstrat.",
    gameMetaDescription: "Aura Clicker este un joc incremental pentru mobil despre Aura, upgrade-uri, outfit-uri, pets și progres offline.",
    gameOgTitle: "Aura Clicker — Joc GoByde",
    gameOgDescription: "Adună Aura, cumpără upgrade-uri și construiește-ți stilul în primul joc GoByde.",
    heroEyebrow: "Studio independent de jocuri și aplicații mobile",
    heroTitleOne: "Jocuri mobile.",
    heroTitleTwo: "Aplicații utile.",
    heroLead: "Suntem GoByde. Primul nostru joc este Aura Clicker și lucrăm deja la următoarele produse mobile.",
    discoverAura: "Vezi Aura Clicker",
    exploreGames: "Vezi proiectele",
    meetStudio: "Despre GoByde",
    studioVisualLabel: "JOCURI • APLICAȚII • MOBILE",
    studioVisualAria: "GoByde — studio de jocuri și aplicații mobile",
    visualWorlds: "MOBILE",
    visualApps: "APLICAȚII",
    visualGames: "JOCURI",
    independentStudio: "STUDIO INDEPENDENT",
    tickerOne: "JOCURI MOBILE",
    tickerTwo: "APLICAȚII MOBILE",
    tickerThree: "FĂCUTE CU GRIJĂ",
    ourGames: "PROIECTELE NOASTRE",
    firstWorld: "Primul nostru joc.",
    gamesTitle: "Începem cu Aura Clicker.",
    gamesIntro: "Aura Clicker este primul nostru joc. Îl construim pentru sesiuni scurte, progres clar și câteva motive bune să revii.",
    comingSoon: "ÎN LUCRU",
    firstRelease: "PRIMUL JOC",
    viewGame: "Vezi pagina jocului",
    gameTagline: "Adună Aura. Găsește-ți stilul.",
    gameDescription: "Atinge pentru Aura, cumpără upgrade-uri, deblochează outfit-uri și colecționează pets. Joacă câteva minute sau lasă progresul offline să lucreze cât timp ești plecat.",
    zones: "ZONE",
    pets: "PETS",
    languages: "LIMBI",
    soonOn: "ÎN CURÂND PE",
    featureProgressTitle: "Progres clar",
    featureProgressText: "Cumpără upgrade-uri, alege între tap și idle și vezi cum cresc numerele.",
    featureStyleTitle: "Schimbă-ți stilul",
    featureStyleText: "Deblochează outfit-uri și schimbă-ți personajul pe parcurs.",
    featurePetsTitle: "Pets care ajută",
    featurePetsText: "Colecționează Aura Pets și alege bonusul potrivit pentru următorul upgrade.",
    featureAnywhereTitle: "Joacă atunci când poți",
    featureAnywhereText: "Sesiuni scurte și progres offline, făcute pentru telefon.",
    comingSoonLabel: "CE URMEAZĂ",
    comingSoonTitle: "Lucrăm și la următorul joc.",
    comingSoonText: "Nu avem încă multe de arătat. Când va fi gata de prezentat, îl vom pune aici.",
    inDevelopment: "ÎN LUCRU",
    nextGame: "Următorul proiect",
    nextGameText: "Încă nu avem ceva concret de arătat.",
    onRoadmap: "URMEAZĂ",
    anotherWorld: "Un alt joc",
    anotherWorldText: "Revenim cu detalii când avem ceva real de prezentat.",
    followJourney: "Preferăm să arătăm lucruri reale, nu să facem promisiuni. Mai multe în curând.",
    theStudio: "DESPRE NOI",
    studioTitle: "Facem produse mobile<br />pe care vrem să le folosim.",
    studioTextOne: "GoByde este un studio independent de jocuri și aplicații mobile. Ne plac ideile clare, controalele care se simt bine și produsele care nu îți irosesc timpul.",
    studioTextTwo: "Aura Clicker este primul nostru joc. În timp, vrem să construim mai multe produse mobile mici, bine făcute și ușor de înțeles.",
    principleOneTitle: "Începe simplu",
    principleOneText: "Dacă o idee nu se înțelege repede, o mai lucrăm.",
    principleTwoTitle: "Fă-l plăcut",
    principleTwoText: "Fiecare atingere, ecran și reacție trebuie să aibă un motiv.",
    principleThreeTitle: "Respectă timpul oamenilor",
    principleThreeText: "Sesiuni scurte când ai timp, cu progres care continuă și când ești ocupat.",
    contactLabel: "CONTACT",
    contactTitle: "Ai o întrebare<br />sau vrei să vorbim despre un proiect?",
    contactText: "Scrie-ne. Ne-ar plăcea să aflăm ce construiești sau ce idee ai.",
    allGames: "Toate jocurile",
    navFeatures: "Despre joc",
    navGallery: "Capturi",
    navGameplay: "Cum joci",
    navWorld: "Zonele",
    backHome: "Acasă",
    firstGameBy: "PRIMUL JOC GOBYDE",
    gameHeroDescription: "Începi cu un personaj, aduni Aura și deblochezi upgrade-uri, outfit-uri, pets și zone noi.",
    gameTagIncremental: "Incremental",
    gameTagCasual: "Casual",
    gameTagOffline: "Progres offline",
    detailArtLabel: "ADUNĂ AURA. FĂ-ȚI STILUL.",
    theExperience: "DESPRE JOC",
    builtForOneMore: "Făcut pentru încă o rundă.",
    auraPotential: "AURA",
    skillNodes: "NODURI DE SKILL",
    theWorld: "ZONELE",
    everyZoneStory: "Crești, iar jocul se deschide.",
    worldDescription: "Începi în holurile școlii și deblochezi locuri noi pe măsură ce strângi Aura.",
    startingZone: "ÎNCEPUTUL",
    schoolHalls: "Școala",
    levelUp: "URMĂTOAREA ZONĂ",
    bigCity: "Orașul",
    collectAndGrow: "COLECȚIONEAZĂ",
    petsAndRewards: "Pets, cufere și recompense",
    collectionText: "Adună pets, deschide cufere și găsește combinația de bonusuri potrivită.",
    stayTuned: "MAI MULTE ÎN CURÂND",
    auraJourneyStarts: "Aura Clicker este<br />încă în lucru.",
    launchUpdates: "Vom adăuga aici noutăți și linkuri de descărcare când jocul va fi gata.",
    backToGames: "Înapoi la jocuri",
    gameplayLabel: "CUM JOCI",
    gameplayTitle: "Aduni Aura, faci upgrade-uri și crești.",
    gameplayIntro: "Intră pentru câteva tap-uri, ia o decizie și ieși. Când revii, progresul offline te așteaptă.",
    stepEarnTitle: "Adună Aura",
    stepEarnText: "Atinge pentru Aura, păstrează combo-ul și folosește loviturile critice pentru câștiguri mai mari.",
    stepInvestTitle: "Cumpără upgrade-uri",
    stepInvestText: "Alege între producție activă și idle, apoi deblochează outfit-uri care cresc producția.",
    stepBuildTitle: "Adună pets",
    stepBuildText: "Colecționează Aura Pets și alege companionul potrivit pentru felul tău de joc.",
    stepPrestigeTitle: "Resetează pentru bonusuri",
    stepPrestigeText: "Folosește Prestige ca să primești Legacy Aura și bonusuri permanente.",
    connectedSystems: "CE GĂSEȘTI ÎN JOC",
    moreThanClicker: "Ai mai multe moduri să crești.",
    systemsIntro: "Aduni Aura prin tap-uri, upgrade-uri, pets și progres offline.",
    systemComboTitle: "Combo și lovituri critice",
    systemComboText: "Atingerile rapide țin combo-ul activ, iar loviturile critice îți cresc câștigul.",
    systemOfflineTitle: "Progres offline",
    systemOfflineText: "Upgrade-urile idle adună Aura chiar și când nu ești în joc.",
    systemLootTitle: "Cufere și boost-uri",
    systemLootText: "Deschide cufere pentru recompense și bonusuri temporare.",
    systemGoalsTitle: "Obiective zilnice",
    systemGoalsText: "Quest-urile și achievements îți dau un motiv nou să intri în fiecare zi.",
    screensLabel: "CAPTURI DIN JOC",
    screensTitle: "Uite cum arată jocul.",
    screensIntro: "Aura Clicker este făcut pentru telefon: informațiile importante sunt la vedere, iar acțiunile principale sunt la o atingere.",
    screensAria: "Capturi din Aura Clicker pe mobil",
    screenGameplayAlt: "Ecranul principal din Aura Clicker pe mobil",
    screenGameplayTitle: "Ecranul principal",
    screenGameplayText: "Aura, personajul, obiectivul zilei și acțiunile rapide pe același ecran.",
    screenUpgradesAlt: "Panoul de upgrade-uri din Aura Clicker",
    screenUpgradesTitle: "Upgrade-uri",
    screenUpgradesText: "Investește în producția activă sau lasă jocul să adune Aura cât timp ești plecat.",
    screenPetsAlt: "Colecția de Aura Pets pe mobil",
    screenPetsTitle: "Aura Pets",
    screenPetsText: "Compară bonusurile și alege companionul potrivit.",
    screenSkillsAlt: "Arborele de abilități din Aura Clicker",
    screenSkillsTitle: "Arbore de abilități",
    screenSkillsText: "21 de noduri pentru tap-uri, Prestige, evenimente și progres offline.",
    privacyMetaDescription: "Află cum GoByde gestionează datele atunci când vizitezi site-ul sau ne contactezi.",
    privacyOgTitle: "Politica de confidențialitate — GoByde",
    privacyOgDescription: "Informații despre datele prelucrate pe site-ul GoByde.",
    gamePrivacyMetaDescription: "Politica de confidențialitate pentru jocul mobil Aura Clicker, publicat de Gobyde Tech SRL.",
    gamePrivacyOgTitle: "Politica de confidențialitate Aura Clicker",
    gamePrivacyOgDescription: "Cum sunt prelucrate datele atunci când folosești Aura Clicker.",
    privacyEyebrow: "TRANSPARENȚĂ ȘI CONFIDENȚIALITATE",
    privacyTitle: "Politica de<br />confidențialitate.",
    privacyIntro: "Aici explicăm, pe scurt și clar, ce date pot fi prelucrate atunci când vizitezi site-ul GoByde sau ne trimiți un e-mail.",
    lastUpdated: "Ultima actualizare",
    privacySummaryAria: "Pe scurt",
    privacySummaryTitle: "PE SCURT",
    privacySummaryText: "Nu folosim analytics, reclame sau trackere. Site-ul reține local doar limba aleasă de tine.",
    privacyControllerTitle: "Cine este operatorul",
    privacyControllerText: "<strong>Gobyde Tech SRL</strong>, cu sediul în Strada Viitorului, Bloc 26, Sc. B, Ap. 15, Săcele, Județ Brașov, România, CUI 55379166, operează acest site și stabilește modul în care sunt folosite datele descrise în această politică. Pentru orice întrebare privind confidențialitatea, ne poți scrie la <a href=\"mailto:support@gobyde.com\">support@gobyde.com</a>.",
    privacyDataTitle: "Ce date putem prelucra",
    privacyDataIntro: "Site-ul nu are conturi, formulare, analytics sau publicitate. Pot fi prelucrate doar următoarele categorii limitate de date:",
    privacyDataLanguage: "<strong>Preferința de limbă:</strong> alegerea RO sau EN este salvată local în browserul tău.",
    privacyDataEmail: "<strong>Corespondența:</strong> dacă ne scrii, primim adresa ta de e-mail și informațiile pe care alegi să le incluzi în mesaj.",
    privacyDataLogs: "<strong>Date tehnice:</strong> furnizorul care găzduiește site-ul poate genera loguri de securitate și acces, precum adresa IP, tipul browserului, data și ora solicitării.",
    privacyPurposesTitle: "De ce folosim aceste date",
    privacyPurposesText: "Folosim aceste date pentru a afișa site-ul în limba aleasă, pentru a răspunde mesajelor, pentru a menține site-ul sigur și funcțional și pentru a respecta eventualele obligații legale. Baza juridică poate fi executarea solicitării tale, interesul nostru legitim de a opera și proteja site-ul sau o obligație legală, după caz.",
    privacyStorageTitle: "Stocare locală și cookies",
    privacyStorageText: "Site-ul folosește localStorage exclusiv pentru a memora limba selectată. Această preferință nu este folosită pentru urmărire și rămâne în browser până când o schimbi sau ștergi datele site-ului. În prezent nu folosim cookie-uri de analiză, marketing sau publicitate.",
    privacySharingTitle: "Furnizori și destinatari",
    privacySharingText: "Datele pot fi accesibile furnizorilor tehnici necesari pentru găzduirea site-ului și furnizarea serviciului de e-mail. Nu vindem date personale. Dacă un furnizor procesează date în afara Spațiului Economic European, vom folosi garanțiile cerute de legislația aplicabilă.",
    privacyRetentionTitle: "Cât timp păstrăm datele",
    privacyRetentionText: "Preferința de limbă rămâne în browserul tău până când este modificată sau ștearsă. Mesajele sunt păstrate numai atât timp cât este necesar pentru a răspunde și pentru eventuale obligații legale. Logurile tehnice sunt păstrate conform perioadelor stabilite de furnizorul de găzduire și numai atât cât este necesar pentru securitate și funcționare.",
    privacyRightsTitle: "Drepturile tale",
    privacyRightsText: "În condițiile prevăzute de GDPR, poți solicita accesul la date, rectificarea sau ștergerea lor, restricționarea prelucrării, portabilitatea și te poți opune anumitor prelucrări. Ne poți contacta la <a href=\"mailto:support@gobyde.com\">support@gobyde.com</a>. De asemenea, poți depune o plângere la autoritatea competentă pentru protecția datelor, inclusiv ANSPDCP în România.",
    privacyGameTitle: "Politica Aura Clicker",
    privacyGameText: "Această politică se aplică numai site-ului GoByde. Pentru informații despre datele prelucrate de joc, consultă <a href=\"aura-clicker-privacy-policy.html\">Politica de confidențialitate Aura Clicker</a>.",
    websitePrivacyLink: "Confidențialitatea site-ului",
    privacyLink: "Confidențialitate",
    rights: "Toate drepturile rezervate.",
    backTop: "Înapoi sus",
  },
  en: {
    skip: "Skip to content",
    navLabel: "Main navigation",
    mobileNavLabel: "Mobile navigation",
    tickerAria: "What GoByde builds",
    googlePlaySoon: "Google Play — coming soon",
    appStoreSoon: "App Store — coming soon",
    navGames: "Games",
    navComingSoon: "In progress",
    navStudio: "About us",
    navContact: "Contact",
    menu: "Menu",
    metaDescription: "GoByde is an independent mobile game and app studio. Our first game is Aura Clicker.",
    ogTitle: "GoByde — Mobile games and apps",
    ogDescription: "We build mobile games and apps that are easy to use and worth keeping.",
    gameMetaDescription: "Aura Clicker is a mobile incremental game about Aura, upgrades, outfits, pets and offline progress.",
    gameOgTitle: "Aura Clicker — A GoByde game",
    gameOgDescription: "Collect Aura, buy upgrades and build your style in GoByde's first game.",
    heroEyebrow: "Independent mobile game and app studio",
    heroTitleOne: "Mobile games.",
    heroTitleTwo: "Useful apps.",
    heroLead: "We are GoByde. Our first game is Aura Clicker, and we are already working on what comes next.",
    discoverAura: "See Aura Clicker",
    exploreGames: "See our projects",
    meetStudio: "About GoByde",
    studioVisualLabel: "GAMES • APPS • MOBILE",
    studioVisualAria: "GoByde — mobile game and app studio",
    visualWorlds: "MOBILE",
    visualApps: "APPS",
    visualGames: "GAMES",
    independentStudio: "INDEPENDENT STUDIO",
    tickerOne: "MOBILE GAMES",
    tickerTwo: "MOBILE APPS",
    tickerThree: "BUILT WITH CARE",
    ourGames: "OUR PROJECTS",
    firstWorld: "Our first game.",
    gamesTitle: "We are starting with Aura Clicker.",
    gamesIntro: "Aura Clicker is our first game. We are building it around short sessions, clear progress and a few good reasons to come back.",
    comingSoon: "IN PROGRESS",
    firstRelease: "FIRST GAME",
    viewGame: "View the game page",
    gameTagline: "Collect Aura. Find your style.",
    gameDescription: "Tap for Aura, buy upgrades, unlock outfits and collect pets. Play for a few minutes or let offline progress work while you are away.",
    zones: "ZONES",
    pets: "PETS",
    languages: "LANGUAGES",
    soonOn: "COMING SOON TO",
    featureProgressTitle: "Clear progress",
    featureProgressText: "Buy upgrades, choose between tap and idle income, and watch the numbers grow.",
    featureStyleTitle: "Change your style",
    featureStyleText: "Unlock outfits and change your character as you play.",
    featurePetsTitle: "Pets that help",
    featurePetsText: "Collect Aura Pets and choose the bonus that helps with your next upgrade.",
    featureAnywhereTitle: "Play when you can",
    featureAnywhereText: "Short sessions and offline progress, made for your phone.",
    comingSoonLabel: "WHAT'S NEXT",
    comingSoonTitle: "The next game is in progress.",
    comingSoonText: "We do not have much to show yet. When it is ready, we will put it here.",
    inDevelopment: "IN PROGRESS",
    nextGame: "Next project",
    nextGameText: "Nothing concrete to show yet.",
    onRoadmap: "UP NEXT",
    anotherWorld: "Another game",
    anotherWorldText: "We will share details when there is something real to show.",
    followJourney: "We would rather show real work than make promises. More soon.",
    theStudio: "ABOUT US",
    studioTitle: "We build mobile products<br />we want to use.",
    studioTextOne: "GoByde is an independent mobile game and app studio. We care about clear ideas, good controls and products that do not waste your time.",
    studioTextTwo: "Aura Clicker is our first game. Over time, we want to make more small, well-made mobile products that are easy to understand.",
    principleOneTitle: "Start simple",
    principleOneText: "If an idea is not clear quickly, we keep working on it.",
    principleTwoTitle: "Make it feel good",
    principleTwoText: "Every tap, screen and response should have a reason.",
    principleThreeTitle: "Respect people's time",
    principleThreeText: "Short sessions when you have time, with progress that keeps going while you are away.",
    contactLabel: "CONTACT",
    contactTitle: "Have a question<br />or want to talk about a project?",
    contactText: "Send us a message. We would like to hear what you are building or thinking about.",
    allGames: "All games",
    navFeatures: "About the game",
    navGallery: "Screenshots",
    navGameplay: "How to play",
    navWorld: "Zones",
    backHome: "Home",
    firstGameBy: "THE FIRST GOBYDE GAME",
    gameHeroDescription: "Start with one character, collect Aura and unlock upgrades, outfits, pets and new zones.",
    gameTagIncremental: "Incremental",
    gameTagCasual: "Casual",
    gameTagOffline: "Offline progress",
    detailArtLabel: "COLLECT AURA. BUILD YOUR STYLE.",
    theExperience: "ABOUT THE GAME",
    builtForOneMore: "Made for one more round.",
    auraPotential: "AURA",
    skillNodes: "SKILL NODES",
    theWorld: "THE ZONES",
    everyZoneStory: "Keep growing and the game opens up.",
    worldDescription: "Start in the school hallways and unlock new places as you collect Aura.",
    startingZone: "THE START",
    schoolHalls: "The school",
    levelUp: "NEXT ZONE",
    bigCity: "The city",
    collectAndGrow: "COLLECT",
    petsAndRewards: "Pets, chests and rewards",
    collectionText: "Collect pets, open chests and find the right combination of bonuses.",
    stayTuned: "MORE SOON",
    auraJourneyStarts: "Aura Clicker is<br />still in progress.",
    launchUpdates: "We will add news and download links here when the game is ready.",
    backToGames: "Back to games",
    gameplayLabel: "HOW TO PLAY",
    gameplayTitle: "Collect Aura, buy upgrades and grow.",
    gameplayIntro: "Jump in for a few taps, make a choice and leave. When you come back, offline progress is waiting for you.",
    stepEarnTitle: "Collect Aura",
    stepEarnText: "Tap for Aura, keep your combo alive and use critical hits for bigger gains.",
    stepInvestTitle: "Buy upgrades",
    stepInvestText: "Choose between active and idle production, then unlock outfits that increase production.",
    stepBuildTitle: "Collect pets",
    stepBuildText: "Collect Aura Pets and choose the companion that fits how you play.",
    stepPrestigeTitle: "Reset for bonuses",
    stepPrestigeText: "Use Prestige to earn Legacy Aura and unlock permanent bonuses.",
    connectedSystems: "WHAT IS IN THE GAME",
    moreThanClicker: "There is more than tapping.",
    systemsIntro: "Collect Aura through taps, upgrades, pets and offline progress.",
    systemComboTitle: "Combo and critical hits",
    systemComboText: "Fast tapping keeps your combo alive, while critical hits increase your earnings.",
    systemOfflineTitle: "Offline progress",
    systemOfflineText: "Idle upgrades collect Aura even when you are away from the game.",
    systemLootTitle: "Chests and boosts",
    systemLootText: "Open chests for rewards and temporary bonuses.",
    systemGoalsTitle: "Daily goals",
    systemGoalsText: "Quests and achievements give you a new reason to play each day.",
    screensLabel: "GAME SCREENSHOTS",
    screensTitle: "See the game in action.",
    screensIntro: "Aura Clicker is made for your phone: important information stays visible and the main actions are always one tap away.",
    screensAria: "Aura Clicker mobile screenshots",
    screenGameplayAlt: "Aura Clicker main screen on mobile",
    screenGameplayTitle: "Main screen",
    screenGameplayText: "Aura, your character, the daily goal and quick actions on one screen.",
    screenUpgradesAlt: "Aura Clicker upgrades panel",
    screenUpgradesTitle: "Upgrades",
    screenUpgradesText: "Invest in active production or let the game collect Aura while you are away.",
    screenPetsAlt: "Aura Pets collection on mobile",
    screenPetsTitle: "Aura Pets",
    screenPetsText: "Compare bonuses and choose the right companion.",
    screenSkillsAlt: "Aura Clicker skill tree",
    screenSkillsTitle: "Skill tree",
    screenSkillsText: "21 nodes for taps, Prestige, events and offline progress.",
    privacyMetaDescription: "Learn how GoByde handles data when you visit the website or contact us.",
    privacyOgTitle: "Privacy Policy — GoByde",
    privacyOgDescription: "Information about data processed on the GoByde website.",
    gamePrivacyMetaDescription: "Privacy Policy for the Aura Clicker mobile game published by Gobyde Tech SRL.",
    gamePrivacyOgTitle: "Aura Clicker Privacy Policy",
    gamePrivacyOgDescription: "How information is handled when you use Aura Clicker.",
    privacyEyebrow: "TRANSPARENCY AND PRIVACY",
    privacyTitle: "Privacy<br />policy.",
    privacyIntro: "This page explains, briefly and clearly, what data may be processed when you visit the GoByde website or send us an email.",
    lastUpdated: "Last updated",
    privacySummaryAria: "At a glance",
    privacySummaryTitle: "AT A GLANCE",
    privacySummaryText: "We do not use analytics, advertising or trackers. The website only stores your language choice locally.",
    privacyControllerTitle: "Who controls the data",
    privacyControllerText: "<strong>Gobyde Tech SRL</strong>, registered at Strada Viitorului, Building 26, Entrance B, Apartment 15, Săcele, Brașov County, Romania, tax identification number 55379166, operates this website and determines how the data described in this policy is used. For any privacy question, contact us at <a href=\"mailto:support@gobyde.com\">support@gobyde.com</a>.",
    privacyDataTitle: "Data we may process",
    privacyDataIntro: "The website has no accounts, forms, analytics or advertising. Only the following limited categories of data may be processed:",
    privacyDataLanguage: "<strong>Language preference:</strong> your RO or EN choice is stored locally in your browser.",
    privacyDataEmail: "<strong>Correspondence:</strong> if you email us, we receive your email address and any information you choose to include in your message.",
    privacyDataLogs: "<strong>Technical data:</strong> the website hosting provider may generate security and access logs, such as IP address, browser type, and the date and time of a request.",
    privacyPurposesTitle: "Why we use this data",
    privacyPurposesText: "We use this data to display the website in your chosen language, reply to messages, keep the website secure and operational, and comply with legal obligations where applicable. Depending on the context, the legal basis may be taking steps at your request, our legitimate interest in operating and protecting the website, or a legal obligation.",
    privacyStorageTitle: "Local storage and cookies",
    privacyStorageText: "The website uses localStorage only to remember the selected language. This preference is not used for tracking and remains in your browser until you change it or clear the website data. We currently use no analytics, marketing or advertising cookies.",
    privacySharingTitle: "Providers and recipients",
    privacySharingText: "Data may be accessible to the technical providers needed to host the website and deliver our email service. We do not sell personal data. If a provider processes data outside the European Economic Area, we will use the safeguards required by applicable law.",
    privacyRetentionTitle: "How long we keep data",
    privacyRetentionText: "The language preference remains in your browser until it is changed or deleted. Messages are kept only as long as needed to reply and meet any legal obligations. Technical logs are kept according to the hosting provider's retention periods and only as long as needed for security and operation.",
    privacyRightsTitle: "Your rights",
    privacyRightsText: "Subject to the conditions set out in the GDPR, you may request access to, correction or deletion of your data, restriction of processing, data portability, and object to certain processing. Contact us at <a href=\"mailto:support@gobyde.com\">support@gobyde.com</a>. You may also lodge a complaint with the competent data protection authority, including the Romanian ANSPDCP.",
    privacyGameTitle: "Aura Clicker policy",
    privacyGameText: "This policy applies only to the GoByde website. For information about data processed by the game, read the <a href=\"aura-clicker-privacy-policy.html\">Aura Clicker Privacy Policy</a>.",
    websitePrivacyLink: "Website privacy",
    privacyLink: "Privacy",
    rights: "All rights reserved.",
    backTop: "Back to top",
  },
};

const header = document.querySelector("[data-header]");
const menuButton = document.querySelector("[data-menu-toggle]");
const mobileMenu = document.querySelector("[data-mobile-menu]");
const languageButton = document.querySelector("[data-language]");
let currentLanguage = localStorage.getItem("gobyde-language") || "ro";

function setLanguage(language) {
  currentLanguage = language;
  const dictionary = translations[language];
  document.documentElement.lang = language;
  const page = document.body.dataset.page;
  document.title = page === "aura-clicker"
    ? (language === "ro" ? "Aura Clicker — Joc GoByde" : "Aura Clicker — A GoByde game")
    : page === "aura-clicker-privacy-policy"
      ? (language === "ro" ? "Politica de confidențialitate Aura Clicker" : "Aura Clicker Privacy Policy")
    : page === "privacy-policy"
      ? (language === "ro" ? "Politica de confidențialitate — GoByde" : "Privacy Policy — GoByde")
      : (language === "ro" ? "GoByde — Jocuri și aplicații mobile" : "GoByde — Mobile games and apps");

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = dictionary[element.dataset.i18n];
    if (value) element.innerHTML = value;
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((element) => {
    const value = dictionary[element.dataset.i18nAria];
    if (value) element.setAttribute("aria-label", value);
  });
  document.querySelectorAll("[data-i18n-alt]").forEach((element) => {
    const value = dictionary[element.dataset.i18nAlt];
    if (value) element.setAttribute("alt", value);
  });
  document.querySelectorAll("[data-i18n-content]").forEach((element) => {
    const value = dictionary[element.dataset.i18nContent];
    if (value) element.setAttribute("content", value);
  });

  languageButton.innerHTML = language === "ro"
    ? '<span class="language-active">RO</span><span class="language-divider">/</span><span>EN</span>'
    : '<span>RO</span><span class="language-divider">/</span><span class="language-active">EN</span>';
  languageButton.setAttribute("aria-label", language === "ro" ? "Switch to English" : "Schimbă în română");
  localStorage.setItem("gobyde-language", language);
}

function closeMenu() {
  mobileMenu.classList.remove("open");
  menuButton.setAttribute("aria-expanded", "false");
  document.body.classList.remove("menu-open");
}

menuButton.addEventListener("click", () => {
  const isOpen = menuButton.getAttribute("aria-expanded") === "true";
  menuButton.setAttribute("aria-expanded", String(!isOpen));
  mobileMenu.classList.toggle("open", !isOpen);
  document.body.classList.toggle("menu-open", !isOpen);
});

mobileMenu.querySelectorAll("a").forEach((link) => link.addEventListener("click", closeMenu));
languageButton.addEventListener("click", () => setLanguage(currentLanguage === "ro" ? "en" : "ro"));
window.addEventListener("scroll", () => header.classList.toggle("scrolled", window.scrollY > 24), { passive: true });
window.addEventListener("resize", () => { if (window.innerWidth > 820) closeMenu(); });

const observer = new IntersectionObserver(
  (entries) => entries.forEach((entry) => {
    if (entry.isIntersecting) {
      entry.target.classList.add("visible");
      observer.unobserve(entry.target);
    }
  }),
  { threshold: 0.12 },
);

document.querySelectorAll(".reveal").forEach((element) => {
  element.style.setProperty("--delay", `${element.dataset.delay || 0}ms`);
  observer.observe(element);
});

document.querySelector("[data-year]").textContent = new Date().getFullYear();
setLanguage(currentLanguage);
